spring.application.name=market-intelligence

server.port=${PORT:8082}

spring.datasource.url=${DB_URL:jdbc:postgresql://db:5432/market_intelligence}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

openweather.api.key=${OPENWEATHER_API_KEY}
news.api.key=${NEWS_API_KEY}
fmp.api.key=${FMP_API_KEY}
metal.api.key=${METAL_API_KEY}